#!/usr/bin/env python3
"""Generate the "Supported printers" pages from a KLIPSLICE source repository.

Everything is read from the committed HEAD of the source repository, never from
its working tree, so the pages always match exactly one source commit:

- resources/profiles/<Vendor>.json and the machine presets they index. Every
  instantiable printer preset is resolved through its `inherits` chain.
- docs/klipslice/printer-firmware.json, the per-model firmware evidence
  (Klipper/Moonraker status, community mod project, sources).

One Markdown page is written per wiki language (docs/printers.md and
docs/printers.de.md).

The run aborts on any inconsistency, because the page must never list a printer
KLIPSLICE does not target:

- an instantiable preset whose gcode_flavor is not `klipper`,
- a profile model without a firmware entry, or whose entry is not `kept`,
- a `kept` firmware entry without a profile model,
- a kept entry with a verdict that is not a known Klipper status.

Usage:
    python3 scripts/gen_printers.py --source /path/to/KLIPSLICE --docs docs
    python3 scripts/gen_printers.py --source /path/to/KLIPSLICE --docs docs --check

--check writes nothing and exits 1 if the committed pages differ from what the
source commit generates. Requires `git` on PATH.
"""

from __future__ import annotations

import argparse
import io
import json
import re
import subprocess
import sys
import tarfile
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlsplit

# Vendor bundles that are libraries or control files, not printer vendors.
NON_VENDOR_BUNDLES = frozenset({"OrcaFilamentLibrary", "blacklist"})

# Maximum inheritance depth before a chain is treated as a cycle.
MAX_INHERIT_DEPTH = 32

PROFILES_PATH = "resources/profiles"
FIRMWARE_PATH = "docs/klipslice/printer-firmware.json"

# Firmware verdicts a kept model may carry, in display order.
VERDICTS = (
    "STOCK_KLIPPER_MOONRAKER",
    "STOCK_KLIPPER_NO_MOONRAKER",
    "KLIPPER_VIA_ESTABLISHED_MOD",
    "DIY_KLIPPER",
)
CONFIDENCES = ("high", "medium", "low")
FIRMWARE_KEYS = ("vendor", "model", "verdict", "kept", "confidence", "mod_project", "sources")

URL_PATTERN = re.compile(r"https?://[^\s;,()<>\[\]|]+")

TEXT = {
    "en": {
        "title": "Supported printers",
        "intro": (
            "This list is generated by `scripts/gen_printers.py` from one commit of the "
            "KLIPSLICE source repository: the printer profiles in `resources/profiles/` "
            "and the per-model firmware evidence in "
            "`docs/klipslice/printer-firmware.json`. Do not edit it by hand; regenerate it "
            "instead."
        ),
        "klipper_only": (
            "KLIPSLICE ships a system profile only for printers that verifiably run real "
            "Klipper, either from the factory, through an established community mod, or as "
            "a self-built machine. The generator refuses to write this page if a profile "
            "resolves to a G-code flavor other than `klipper`, if a profile model has no "
            "firmware evidence, or if the evidence and the profiles disagree."
        ),
        "moonraker_title": "Connection",
        "moonraker": (
            "KLIPSLICE uses Moonraker as its only print host. Printers from vendors with "
            "their own Klipper integration connect through Moonraker as well, not through "
            "a vendor cloud or a vendor-specific protocol. Where the stock firmware does "
            "not expose Moonraker, the *Firmware* column says so and names the community "
            "project that adds it."
        ),
        "legend_title": "Firmware status",
        "legend_intro": "Each model carries one of these statuses:",
        "verdicts": {
            "STOCK_KLIPPER_MOONRAKER": "Klipper + Moonraker (stock)",
            "STOCK_KLIPPER_NO_MOONRAKER": "Klipper (stock), Moonraker via root or mod",
            "KLIPPER_VIA_ESTABLISHED_MOD": "Real Klipper via established mod",
            "DIY_KLIPPER": "DIY Klipper",
        },
        "verdict_help": {
            "STOCK_KLIPPER_MOONRAKER": (
                "The printer runs Klipper and Moonraker as delivered. Vendor firmware is "
                "often a patched Klipper; it counts as long as Moonraker is reachable."
            ),
            "STOCK_KLIPPER_NO_MOONRAKER": (
                "The printer runs a Klipper-based firmware as delivered, but Moonraker has "
                "to be enabled by rooting the printer or installing a community mod "
                "(linked in the *Mod project* column where one exists)."
            ),
            "KLIPPER_VIA_ESTABLISHED_MOD": (
                "The stock firmware is not real Klipper. An established community project "
                "replaces or extends it with Klipper and Moonraker (linked in the *Mod "
                "project* column)."
            ),
            "DIY_KLIPPER": (
                "A kit or self-built design that is set up with Klipper and Moonraker by "
                "the builder."
            ),
        },
        "confidence_title": "Confidence",
        "confidence_help": (
            "How strong the evidence for the firmware status is, as rated when the model "
            "was researched (*high*, *medium* or *low*). Models rated *low* are kept because "
            "the available evidence points to Klipper, but that evidence is thin; reports "
            "from owners are welcome."
        ),
        "confidences": {"high": "high", "medium": "medium", "low": "low"},
        "own_title": "Your own Klipper printer",
        "own": [
            "A printer does not need a system profile to work with KLIPSLICE. Self-built "
            "machines and converted printers (for example a Marlin printer that now runs "
            "Klipper on a new board or a Raspberry Pi) are first-class:",
            "",
            "- **Generic Klipper Printer** (vendor *Custom Printer*): a neutral starting "
            "point for any Klipper machine. Select it in the printer selection, then set "
            "bed size, nozzle and limits for your machine. **Generic ToolChanger Printer** "
            "is the equivalent for tool changers.",
            "- **Create printer**: open the printer drop-down on the *Prepare* tab and "
            "choose *Create printer*. The *Create Printer/Nozzle* dialog creates a printer "
            "from a template or from the current printer, with any vendor and model name, "
            "including a custom one typed in.",
            "",
            "Either way the G-code flavor is Klipper and the print host is Moonraker. See "
            "[Klipper setup](klipper-setup.md) for the macros KLIPSLICE expects. To ship a "
            "profile for a Klipper printer that is missing here, see "
            "[Contributing](contributing.md#printer-profiles).",
        ],
        "summary_title": "Summary",
        "vendors": "Vendors",
        "models": "Printer models",
        "presets": "Printer presets (model × nozzle)",
        "status_col": "Firmware status",
        "vendor_col": "Vendor",
        "model_col": "Model",
        "nozzle_col": "Nozzles (mm)",
        "firmware_col": "Firmware",
        "mod_col": "Mod project",
        "confidence_col": "Confidence",
        "sources_col": "Sources",
        "count_col": "Models",
        "generated_from": "Generated from source commit",
    },
    "de": {
        "title": "Unterstützte Drucker",
        "intro": (
            "Diese Liste erzeugt `scripts/gen_printers.py` aus genau einem Commit des "
            "KLIPSLICE-Quellrepositorys: aus den Druckerprofilen in `resources/profiles/` "
            "und den Firmware-Nachweisen je Modell in "
            "`docs/klipslice/printer-firmware.json`. Nicht von Hand bearbeiten, sondern "
            "neu generieren."
        ),
        "klipper_only": (
            "KLIPSLICE liefert ein Systemprofil nur für Drucker, die nachweislich echtes "
            "Klipper ausführen: ab Werk, über einen etablierten Community-Mod oder als "
            "Selbstbau. Der Generator bricht ab, sobald ein Profil bei einem anderen "
            "G-Code-Dialekt als `klipper` landet, ein Profilmodell keinen Firmware-Nachweis "
            "hat oder Nachweise und Profile nicht zusammenpassen."
        ),
        "moonraker_title": "Verbindung",
        "moonraker": (
            "KLIPSLICE nutzt Moonraker als einzigen Druck-Host. Auch Drucker von "
            "Herstellern mit eigener Klipper-Integration werden über Moonraker angebunden, "
            "nicht über eine Hersteller-Cloud oder ein herstellereigenes Protokoll. Wo die "
            "Werks-Firmware Moonraker nicht anbietet, steht das in der Spalte *Firmware*, "
            "zusammen mit dem Community-Projekt, das Moonraker nachrüstet."
        ),
        "legend_title": "Firmware-Status",
        "legend_intro": "Jedes Modell hat genau einen dieser Status:",
        "verdicts": {
            "STOCK_KLIPPER_MOONRAKER": "Klipper + Moonraker (ab Werk)",
            "STOCK_KLIPPER_NO_MOONRAKER": "Klipper (ab Werk), Moonraker per Root oder Mod",
            "KLIPPER_VIA_ESTABLISHED_MOD": "Echtes Klipper per etabliertem Mod",
            "DIY_KLIPPER": "Klipper im Selbstbau",
        },
        "verdict_help": {
            "STOCK_KLIPPER_MOONRAKER": (
                "Der Drucker läuft im Auslieferungszustand mit Klipper und Moonraker. "
                "Hersteller-Firmware ist oft ein angepasstes Klipper; das zählt, solange "
                "Moonraker erreichbar ist."
            ),
            "STOCK_KLIPPER_NO_MOONRAKER": (
                "Der Drucker läuft ab Werk mit einer Klipper-basierten Firmware, Moonraker "
                "muss aber per Root-Zugang oder Community-Mod freigeschaltet werden (in der "
                "Spalte *Mod-Projekt* verlinkt, sofern vorhanden)."
            ),
            "KLIPPER_VIA_ESTABLISHED_MOD": (
                "Die Werks-Firmware ist kein echtes Klipper. Ein etabliertes "
                "Community-Projekt ersetzt oder erweitert sie um Klipper und Moonraker (in "
                "der Spalte *Mod-Projekt* verlinkt)."
            ),
            "DIY_KLIPPER": (
                "Ein Bausatz oder Selbstbau-Design, das der Erbauer mit Klipper und "
                "Moonraker einrichtet."
            ),
        },
        "confidence_title": "Sicherheit",
        "confidence_help": (
            "Wie belastbar der Nachweis für den Firmware-Status ist, bewertet bei der "
            "Recherche zum Modell (*hoch*, *mittel* oder *niedrig*). Modelle mit *niedrig* "
            "bleiben in der Liste, weil die verfügbaren Hinweise auf Klipper zeigen, die "
            "Beleglage aber dünn ist; Rückmeldungen von Besitzern sind willkommen."
        ),
        "confidences": {"high": "hoch", "medium": "mittel", "low": "niedrig"},
        "own_title": "Eigener Klipper-Drucker",
        "own": [
            "Ein Drucker braucht kein Systemprofil, um mit KLIPSLICE zu funktionieren. "
            "Selbstbauten und umgebaute Drucker (etwa ein Marlin-Drucker, der jetzt mit "
            "neuem Board oder Raspberry Pi unter Klipper läuft) sind vollwertig "
            "unterstützt:",
            "",
            "- **Generic Klipper Printer** (Hersteller *Custom Printer*): ein neutraler "
            "Ausgangspunkt für jede Klipper-Maschine. In der Druckerauswahl wählen, dann "
            "Bettgröße, Düse und Grenzwerte der eigenen Maschine eintragen. **Generic "
            "ToolChanger Printer** ist das Gegenstück für Werkzeugwechsler.",
            "- **Create printer**: im Tab *Prepare* das Drucker-Auswahlmenü öffnen und "
            "*Create printer* wählen. Der Dialog *Create Printer/Nozzle* legt einen Drucker "
            "aus einer Vorlage oder auf Basis des aktuellen Druckers an, mit beliebigem "
            "Hersteller- und Modellnamen, auch frei eingetippt.",
            "",
            "In beiden Fällen ist der G-Code-Dialekt Klipper und der Druck-Host Moonraker. "
            "Welche Makros KLIPSLICE erwartet, steht unter "
            "[Klipper-Einrichtung](klipper-setup.md). Wie man ein Profil für einen hier "
            "fehlenden Klipper-Drucker beisteuert, steht unter "
            "[Mitwirken](contributing.md#printer-profiles).",
        ],
        "summary_title": "Übersicht",
        "vendors": "Hersteller",
        "models": "Druckermodelle",
        "presets": "Druckerprofile (Modell × Düse)",
        "status_col": "Firmware-Status",
        "vendor_col": "Hersteller",
        "model_col": "Modell",
        "nozzle_col": "Düsen (mm)",
        "firmware_col": "Firmware",
        "mod_col": "Mod-Projekt",
        "confidence_col": "Sicherheit",
        "sources_col": "Quellen",
        "count_col": "Modelle",
        "generated_from": "Erzeugt aus Quell-Commit",
    },
}

OUTPUT_NAMES = {"en": "printers.md", "de": "printers.de.md"}


class ProfileError(Exception):
    """Raised when the source data is inconsistent or cannot be read."""


@dataclass
class Firmware:
    verdict: str
    confidence: str
    mod_links: list[str]
    sources: list[str]


@dataclass
class Model:
    name: str
    nozzles: set[str] = field(default_factory=set)
    presets: int = 0
    firmware: Firmware | None = None


@dataclass
class Vendor:
    name: str
    models: list[Model]


# ---------------------------------------------------------------------------
# Source repository access (read-only, committed HEAD only)
# ---------------------------------------------------------------------------


def git(source: Path, *args: str) -> bytes:
    try:
        result = subprocess.run(
            ["git", "-C", str(source), *args],
            check=False,
            capture_output=True,
        )
    except OSError as exc:
        raise ProfileError(f"cannot run git: {exc}") from exc
    if result.returncode != 0:
        message = result.stderr.decode("utf-8", "replace").strip()
        raise ProfileError(f"git {' '.join(args)} failed in {source}: {message}")
    return result.stdout


def source_commit(source: Path) -> str:
    return git(source, "rev-parse", "--short=10", "HEAD").decode("ascii").strip()


def export_profiles(source: Path, commit: str, target: Path) -> Path:
    """Extract resources/profiles at `commit` into `target`; return the profiles dir."""
    archive = git(source, "archive", "--format=tar", commit, PROFILES_PATH)
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:") as tar:
        tar.extractall(target, filter="data")
    profiles = target / PROFILES_PATH
    if not profiles.is_dir():
        raise ProfileError(f"{PROFILES_PATH} missing at {commit}; --source must be a KLIPSLICE repository")
    return profiles


# ---------------------------------------------------------------------------
# Printer profiles
# ---------------------------------------------------------------------------


def load_json(path: Path) -> dict:
    try:
        with path.open(encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        raise ProfileError(f"cannot read {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ProfileError(f"{path}: top level is not a JSON object")
    return data


def resolve(name: str, presets: dict[str, dict], key: str, vendor: str):
    """Return `key` for preset `name`, following `inherits` until it is set."""
    current = name
    for _ in range(MAX_INHERIT_DEPTH):
        preset = presets.get(current)
        if preset is None:
            raise ProfileError(f"{vendor}: preset '{current}' (reached from '{name}') is not indexed")
        if key in preset:
            return preset[key]
        parent = preset.get("inherits", "")
        if not parent:
            return None
        current = parent
    raise ProfileError(f"{vendor}: inheritance of '{name}' exceeds {MAX_INHERIT_DEPTH} levels (cycle?)")


def nozzle_values(raw) -> list[str]:
    if raw is None:
        return []
    items = raw if isinstance(raw, list) else str(raw).split(";")
    return [str(item).strip() for item in items if str(item).strip()]


def nozzle_sort_key(value: str) -> float:
    try:
        return float(value)
    except ValueError as exc:
        raise ProfileError(f"nozzle diameter '{value}' is not a number") from exc


def read_vendor(bundle: Path) -> Vendor | None:
    index = load_json(bundle)
    model_entries = index.get("machine_model_list") or []
    if not model_entries:
        return None
    vendor_name = str(index.get("name") or bundle.stem)
    vendor_dir = bundle.parent / bundle.stem

    presets: dict[str, dict] = {}
    for entry in index.get("machine_list") or []:
        sub_path = entry.get("sub_path")
        if not sub_path:
            raise ProfileError(f"{vendor_name}: machine_list entry without sub_path: {entry}")
        data = load_json(vendor_dir / sub_path)
        preset_name = data.get("name")
        if not preset_name:
            raise ProfileError(f"{vendor_name}: {sub_path} has no 'name'")
        presets[preset_name] = data

    models = {str(entry["name"]): Model(str(entry["name"])) for entry in model_entries if entry.get("name")}

    for preset_name, data in presets.items():
        if str(data.get("instantiation", "")).lower() != "true":
            continue
        flavor = resolve(preset_name, presets, "gcode_flavor", vendor_name)
        if flavor != "klipper":
            raise ProfileError(
                f"{vendor_name}: printer preset '{preset_name}' resolves to gcode_flavor={flavor!r}, not 'klipper'"
            )
        model_name = resolve(preset_name, presets, "printer_model", vendor_name)
        if not model_name:
            raise ProfileError(f"{vendor_name}: printer preset '{preset_name}' has no printer_model")
        model = models.get(str(model_name))
        if model is None:
            raise ProfileError(
                f"{vendor_name}: printer preset '{preset_name}' names model '{model_name}', "
                "which is not in machine_model_list"
            )
        model.presets += 1
        model.nozzles.update(nozzle_values(resolve(preset_name, presets, "nozzle_diameter", vendor_name)))

    listed = [model for model in models.values() if model.presets > 0]
    if not listed:
        return None
    listed.sort(key=lambda m: m.name.casefold())
    return Vendor(vendor_name, listed)


def collect_profiles(profiles: Path) -> list[Vendor]:
    vendors = []
    for bundle in sorted(profiles.glob("*.json"), key=lambda p: p.stem.casefold()):
        if bundle.stem in NON_VENDOR_BUNDLES:
            continue
        vendor = read_vendor(bundle)
        if vendor is not None:
            vendors.append(vendor)
    if not vendors:
        raise ProfileError(f"no printer vendors found under {PROFILES_PATH}")
    return vendors


# ---------------------------------------------------------------------------
# Firmware evidence
# ---------------------------------------------------------------------------


def parse_firmware(raw: bytes) -> dict[str, Firmware]:
    """Return the kept firmware entries keyed by model name."""
    try:
        entries = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ProfileError(f"{FIRMWARE_PATH}: invalid JSON: {exc}") from exc
    if not isinstance(entries, list):
        raise ProfileError(f"{FIRMWARE_PATH}: top level is not a JSON array")

    seen: set[str] = set()
    kept: dict[str, Firmware] = {}
    for position, entry in enumerate(entries):
        where = f"{FIRMWARE_PATH}[{position}]"
        if not isinstance(entry, dict):
            raise ProfileError(f"{where}: entry is not an object")
        missing = [key for key in FIRMWARE_KEYS if key not in entry]
        if missing:
            raise ProfileError(f"{where}: missing keys {missing}")
        model = entry["model"]
        if not isinstance(model, str) or not model:
            raise ProfileError(f"{where}: 'model' must be a non-empty string")
        if model in seen:
            raise ProfileError(f"{where}: duplicate model '{model}'")
        seen.add(model)
        if not isinstance(entry["kept"], bool):
            raise ProfileError(f"{where} ({model}): 'kept' must be true or false")
        if not entry["kept"]:
            continue

        verdict = entry["verdict"]
        if verdict not in VERDICTS:
            raise ProfileError(f"{where} ({model}): kept with verdict {verdict!r}, expected one of {VERDICTS}")
        confidence = entry["confidence"]
        if confidence not in CONFIDENCES:
            raise ProfileError(f"{where} ({model}): unknown confidence {confidence!r}")
        sources = entry["sources"]
        if not isinstance(sources, list) or not sources:
            raise ProfileError(f"{where} ({model}): a kept model needs at least one source")
        for url in sources:
            if not isinstance(url, str) or URL_PATTERN.fullmatch(url) is None:
                raise ProfileError(f"{where} ({model}): source {url!r} is not a plain http(s) URL")
        mod_project = entry["mod_project"]
        if not isinstance(mod_project, str):
            raise ProfileError(f"{where} ({model}): 'mod_project' must be a string")
        mod_links = unique(URL_PATTERN.findall(mod_project))
        if verdict == "KLIPPER_VIA_ESTABLISHED_MOD" and not mod_links:
            raise ProfileError(f"{where} ({model}): verdict {verdict} needs a mod project URL")
        kept[model] = Firmware(verdict, confidence, mod_links, list(sources))
    return kept


def unique(items: list[str]) -> list[str]:
    result: list[str] = []
    for item in items:
        if item not in result:
            result.append(item)
    return result


def attach_firmware(vendors: list[Vendor], firmware: dict[str, Firmware]) -> None:
    listed: set[str] = set()
    for vendor in vendors:
        for model in vendor.models:
            entry = firmware.get(model.name)
            if entry is None:
                raise ProfileError(
                    f"{vendor.name}: model '{model.name}' has a profile but no kept entry in {FIRMWARE_PATH}"
                )
            model.firmware = entry
            listed.add(model.name)
    orphaned = sorted(set(firmware) - listed, key=str.casefold)
    if orphaned:
        raise ProfileError(f"kept in {FIRMWARE_PATH} but no printer profile: {', '.join(orphaned)}")


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def anchor(name: str) -> str:
    slug = "".join(ch if ch.isalnum() else "-" for ch in name.casefold())
    while "--" in slug:
        slug = slug.replace("--", "-")
    return "vendor-" + slug.strip("-")


def cell(text: str) -> str:
    return text.replace("|", "\\|")


def host_label(url: str) -> str:
    host = urlsplit(url).hostname or url
    return host[4:] if host.startswith("www.") else host


def link_label(url: str) -> str:
    parts = urlsplit(url)
    segments = [segment for segment in parts.path.split("/") if segment]
    if parts.hostname == "github.com" and len(segments) >= 2:
        return f"{segments[0]}/{segments[1]}"
    return host_label(url)


def link_list(urls: list[str], label) -> str:
    labels = [label(url) for url in urls]
    rendered = []
    for position, (url, text) in enumerate(zip(urls, labels)):
        if labels.count(text) > 1:
            text = f"{text} ({labels[:position + 1].count(text)})"
        rendered.append(f"[{cell(text)}]({url})")
    return "<br>".join(rendered)


def render(vendors: list[Vendor], lang: str, commit: str) -> str:
    t = TEXT[lang]
    models = [model for vendor in vendors for model in vendor.models]
    preset_total = sum(model.presets for model in models)
    status_counts = {verdict: 0 for verdict in VERDICTS}
    for model in models:
        status_counts[model.firmware.verdict] += 1

    lines = [
        "<!-- Generated by scripts/gen_printers.py. Do not edit by hand. -->",
        "",
        f"# {t['title']}",
        "",
        t["intro"],
        "",
        f"!!! info \"{t['moonraker_title']}\"",
        "",
        f"    {t['moonraker']}",
        "",
        t["klipper_only"],
        "",
        f"## {t['summary_title']}",
        "",
        f"| {t['vendors']} | {t['models']} | {t['presets']} |",
        "|---:|---:|---:|",
        f"| {len(vendors)} | {len(models)} | {preset_total} |",
        "",
        f"| {t['status_col']} | {t['count_col']} |",
        "|---|---:|",
    ]
    for verdict in VERDICTS:
        lines.append(f"| {t['verdicts'][verdict]} | {status_counts[verdict]} |")
    lines += [
        "",
        f"| {t['vendor_col']} | {t['count_col']} |",
        "|---|---:|",
    ]
    for vendor in vendors:
        lines.append(f"| [{cell(vendor.name)}](#{anchor(vendor.name)}) | {len(vendor.models)} |")
    lines += [
        "",
        f"## {t['legend_title']} {{ #firmware-status }}",
        "",
        t["legend_intro"],
        "",
    ]
    for verdict in VERDICTS:
        lines += [f"{t['verdicts'][verdict]}", f":   {t['verdict_help'][verdict]}", ""]
    lines += [f"{t['confidence_title']}", f":   {t['confidence_help']}", ""]
    lines += [f"## {t['own_title']} {{ #own-printer }}", "", *t["own"], ""]

    header = (
        f"| {t['model_col']} | {t['nozzle_col']} | {t['firmware_col']} | {t['mod_col']} "
        f"| {t['confidence_col']} | {t['sources_col']} |"
    )
    for vendor in vendors:
        lines += [f"## {vendor.name} {{ #{anchor(vendor.name)} }}", "", header, "|---|---|---|---|---|---|"]
        for model in vendor.models:
            fw = model.firmware
            nozzles = ", ".join(sorted(model.nozzles, key=nozzle_sort_key))
            mods = link_list(fw.mod_links, link_label) if fw.mod_links else "–"
            lines.append(
                f"| {cell(model.name)} | {nozzles} | {t['verdicts'][fw.verdict]} | {mods} "
                f"| {t['confidences'][fw.confidence]} | {link_list(fw.sources, link_label)} |"
            )
        lines.append("")
    lines += [f"<small>{t['generated_from']} `{commit}`.</small>", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", required=True, type=Path, help="path to a KLIPSLICE source repository")
    parser.add_argument("--docs", required=True, type=Path, help="wiki docs directory to write into")
    parser.add_argument("--check", action="store_true", help="compare only, write nothing; exit 1 on difference")
    args = parser.parse_args()

    if not args.docs.is_dir():
        print(f"error: {args.docs} is not a directory", file=sys.stderr)
        return 2
    try:
        commit = source_commit(args.source)
        with tempfile.TemporaryDirectory(prefix="gen_printers_") as scratch:
            vendors = collect_profiles(export_profiles(args.source, commit, Path(scratch)))
        firmware = parse_firmware(git(args.source, "show", f"{commit}:{FIRMWARE_PATH}"))
        attach_firmware(vendors, firmware)
    except ProfileError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    stale = []
    for lang, filename in OUTPUT_NAMES.items():
        target = args.docs / filename
        content = render(vendors, lang, commit)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.is_file() else None
            if current != content:
                stale.append(str(target))
        else:
            target.write_text(content, encoding="utf-8")
            print(f"wrote {target}")
    if stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
